### ISSUE TITLE
remove 'sh' parameter from FFT.fft

### ISSUE THREAD

**Issue by amigalemming** [AccelerateHS/accelerate-fft#2]
The 'sh' parameter is not needed for planning the FFT, thus I propose to remove it. This would allow to re-use the same plan for arrays with arbitrary global shape.

**Comment by Haskell-mouse** [comment]
I have tried to do this just now, but without any success. 
I did it for native and ptx cases (you can write any "sh" value and it will be ignored). 

With interpreter problem is that i cant restore innermost dimensions from "Exp sh" value. 
Maybe it's a lack of my knowledge of haskell ( 
Maybe there is solution through Template Haskell. 

Another way - to write 3 functions fft1, fft2, fft3, but it is ugly i think....

**Comment by tmcdonell** [comment]
Yes, the reason the `sh` parameter is still required as a real Haskell value is explained [here](https://github.com/AccelerateHS/accelerate-fft/blob/413c7a170d592165f20e6e114afbd917b6569a3e/Data/Array/Accelerate/Math/FFT.hs#L225).

That is a very naive implementation though, so if we can replace it with a real algorithm then perhaps we can avoid this problem. I think [this package](http://hackage.haskell.org/package/accelerate-fourier) might have such an implementation, so maybe we should use that instead?

On the other hand, there is little reason to be using the naive implementation at all (at least in the current form; a better algorithm might perform well enough to be useful), so maybe it should be removed and have a requirement that the CUDA or FFTW foreign libraries are used instead?

**Comment by Haskell-mouse** [comment]
I think that there is should be implementation for interpreter - it is very useful sometimes. For example i cant properly build llvm-4 in my win10(i tried for 2 days, lol....), but i still can use accelerate-fft library and test my code with interpreter on my laptop. 

I think, that i can try to use accelerate-fourier to make implementation for interpreter without sh param.

**Comment by amigalemming** [comment]
On Thu, 17 Aug 2017, Rinat Striungis wrote:

> I think, that i can try to use accelerate-fourier to make implementation 
> for interpreter without sh param.

The accelerate-fourier library provides a full implementation of 
Fast-Fourier transformations for all data set sizes in plain Accelerate 
code.

**Comment by Haskell-mouse** [comment]
That is nice :-)
So - i ll try to use it to replace "interpreter fft" function.

**Comment by tmcdonell** [comment]
@Haskell-mouse by the way, @yuhangwang has had some progress installing LLVM on windows, and has written up some instructions [here](https://github.com/llvm-hs/llvm-hs/issues/123#issuecomment-323892741); maybe that has some useful points for you too.

**Comment by amigalemming** [comment]
On Wed, 23 Aug 2017, Trevor L. McDonell wrote:

> @Haskell-mouse by the way, @yuhangwang has had some progress installing LLVM on windows, and has written up some
> instructions here; maybe that has some useful points for you too.

Last time, I tried, I succeeded building LLVM-3.8 on MSYS2.

**Comment by Haskell-mouse** [comment]
@tmcdonell , thank you ! 
I ll try it later due to very busy right now.

I tried to build llvm-4.0, but it has been built successfully only without recommended by llvm-hs flags, and llvm-hs didnt work. 
So... thank you again =)
